### ISSUE TITLE
Credentials error if "username" is missing

### ISSUE THREAD

**Issue by Pschittt** [iRay/TeleTor#3]
Hello,

On the config file, you need to complete the "auth" parameters with ID, username, first_name, last_name.

If the "username" parameter is not set, it raises an exception : 
 `    credentials = zip([user['id'], user['username'], user['first_name'], user['last_name']],
KeyError: 'username'
ERROR:root:on_close() called due to KeyError: 'username'`

Make "ID" parameter as mandatory, and the other 3 as optional (check if they are set in the config.yaml file).

**Comment by iRay** [comment]
@Pschittt Thank you for your attention.
“telepot” library was used in the project. And i’m not satisfied with it. The library has issues with “design”
 and it was a mistate to use it. Also it was a test project to work with telegram api hence there is no unit tests or proper validation in some cases.
So that the project is abandoned. But once. again - thank you for your attention))
